# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 10:20
from __future__ import unicode_literals

import attachments.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('attachment_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=attachments.models.attachment_upload, verbose_name='attachment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('safe', models.BooleanField(default=False, verbose_name='safe')),
                ('mime_type', models.CharField(blank=True, help_text='leave empty to handle by file extension', max_length=50, null=True, verbose_name='mime type')),
                ('display_name', models.CharField(blank=True, help_text='displayed as link text for attachment.', max_length=256, null=True, verbose_name='display name')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_attachments', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'ordering': ['-created'],
                'permissions': (('delete_foreign_attachments', 'Can delete foreign attachments'),),
            },
        ),
    ]
